CREATE TABLE EMPLOYEE(
	EMPLOYEEID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    EMAILADDRESS VARCHAR(40) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DOB DATE NOT NULL,
    ADDRESSID INT NOT NULL,
    CLINICID INT NOT NULL,
    UNIVERSITYID INT NULL,
    FOREIGN KEY(ADDRESSID) REFERENCES ADDRESS(ADDRESSID),
    FOREIGN KEY (CLINICID) REFERENCES CLINIC(CLINICID),
    FOREIGN KEY (UNIVERSITYID) REFERENCES UNIVERSITY(UNIVERSITYID)
);
CREATE TABLE ADDRESS(
	ADDRESSID INT PRIMARY KEY,
    STREET VARCHAR(40) NOT NULL,
    ZIPCODE CHAR(5) NOT NULL,
    STATE CHAR(2) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    ADTYPE VARCHAR(12) NOT NULL
);

CREATE TABLE CLINIC(
CLINICID INT PRIMARY KEY,
ADDRESSID INT NOT NULL,
FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(ADDRESSID)
);

CREATE TABLE UNIVERSITY(
	UNIVERSITYID INT PRIMARY KEY,
	UNIVERSITYNAME VARCHAR(40) NOT NULL,
	STATE CHAR(2)
);

CREATE TABLE PHYSICIAN(
	PHYSICIANID INT PRIMARY KEY,
    EMPLOYEEID INT NOT NULL,
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE SPECIALTY(
	SPECIALTYID INT PRIMARY KEY,
    SPECIALTY VARCHAR(20) NOT NULL
);

CREATE TABLE NURSE(
	NURSEID INT PRIMARY KEY,
    EMPLOYEEID INT NOT NULL,
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE PATIENT(
	PATIENTID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DOB DATE NOT NULL
);
CREATE TABLE COMPANY(
	COMPANYID INT PRIMARY KEY,
    COMPANYNAME VARCHAR(40) NOT NULL
);

CREATE TABLE EQUIPMENT(
	EQUIPMENTID INT PRIMARY KEY,
    EQUIPMENTNAME VARCHAR(20) NOT NULL,
    COMPANYID INT NOT NULL,
    FOREIGN KEY (COMPANYID) REFERENCES COMPANY(COMPANYID)
);

CREATE TABLE CERTIFICATE(
	CERTIFICATEID INT PRIMARY KEY,
    CERTIFICATETYPE VARCHAR(40) NOT NULL,
    CERTIFICATENAME VARCHAR(50) NOT NULL
);

CREATE TABLE HELPDESK(
	HELPDESKID INT PRIMARY KEY,
    APPOINTMENTSTART TIME NOT NULL,
    APPOINTMENTEND TIME NOT NULL,
    PHYSICIANID INT NOT NULL,
    PATIENTID INT NOT NULL,
    FOREIGN KEY (PHYSICIANID) REFERENCES PHYSICIAN (PHYSICIANID),
    FOREIGN KEY (PATIENTID) REFERENCES PATIENT (PATIENTID)
);

CREATE TABLE CHECKUP(
	CHECKUPID INT PRIMARY KEY,
    HEIGHT DECIMAL(5,2) NOT NULL,
    BLOODPRESSURE VARCHAR(6) NOT NULL,
    WEIGHT DECIMAL(5,2) NOT NULL,
    TEMPERATURE INT NOT NULL,
    NURSEID INT NOT NULL,
    PATIENTID INT NOT NULL    
);

CREATE TABLE DIAGNOSIS(
	PHYSICIANID INT NOT NULL,
    PATIENTID INT NOT NULL,
    DIAGNOSIS VARCHAR(30) NULL,
    CONSTRAINT PK_DIAGNOSIS PRIMARY KEY(PHYSICIANID, PATIENTID)
);

CREATE TABLE NURSEEQUIPMENT(
	NURSEID INT NOT NULL,
    EQUIPMENTID INT NOT NULL,
    FOREIGN KEY (NURSEID) REFERENCES NURSE (NURSEID),
    FOREIGN KEY (EQUIPMENTID) REFERENCES EQUIPMENT(EQUIPMENTID),
    CONSTRAINT PK_NURSEEQUIPMENT PRIMARY KEY (NURSEID, EQUIPMENTID)
);

CREATE TABLE NURSECERTIFICATION(
	NURSEID INT NOT NULL,
    CERTIFICATEID INT NOT NULL,
    FOREIGN KEY (NURSEID) REFERENCES NURSE (NURSEID),
    FOREIGN KEY (CERTIFICATEID) REFERENCES CERTIFICATE (CERTIFICATEID),
    CONSTRAINT PK_NURSECERT PRIMARY KEY (NURSEID, CERTIFICATEID)
);

CREATE TABLE PHYSICIANSPECIALTY(
	PHYSICIANID INT NOT NULL,
    SPECIALTYID INT NOT NULL,
    FOREIGN KEY (PHYSICIANID) REFERENCES PHYSICIAN (PHYSICIANID),
    FOREIGN KEY (SPECIALTYID) REFERENCES SPECIALTY (SPECIALTYID),
    CONSTRAINT PK_PHYSICIANSPECIALTY PRIMARY KEY (PHYSICIANID, SPECIALTYID)
);
CREATE TABLE PHYSICIANEQUIPMENT(
	PHYSICIANID INT NOT NULL,
    EQUIPMENTID INT NOT NULL,
    FOREIGN KEY (PHYSICIANID) REFERENCES PHYSICIAN (PHYSICIANID),
    FOREIGN KEY (EQUIPMENTID) REFERENCES EQUIPMENT(EQUIPMENTID),
    CONSTRAINT PK_PHYSICIANEQUIPMENT PRIMARY KEY (PHYSICIANID, EQUIPMENTID)
);




